steps:
  # Build the API container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.api', '-t', 'gcr.io/$PROJECT_ID/crop-api-$_ENV', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crop-api-$_ENV']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crop-api-$_ENV'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crop-api-$_ENV'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '2'
      - '--port'
      - '8080'
      - '--timeout'
      - '3600'

  # Set IAM policy to allow public access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'crop-api-$_ENV'
      - '--region'
      - 'southamerica-east1'
      - '--member'
      - 'allUsers'
      - '--role'
      - 'roles/run.invoker'

images:
  - 'gcr.io/$PROJECT_ID/crop-api-$_ENV' 