[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true
enableStaticServing = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#181082"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 